# Netlify File Settings for Alpha Hugo theme
# Documentation: https://docs.netlify.com/configure-builds/file-based-configuration/
# 
# Security headers are set by the file `static/_headers`
#
[build.environment]
    HUGO_VERSION = "0.150.0" 
